jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        distribution: zulu
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      name: Checkout current commit
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - continue-on-error: true
      name: Cache Bazel repositories
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
      with:
        key: bazel-repositories-${{hashFiles('**/WORKSPACE', '**.bzl')}}
        path: ~/bazel-repository-cache
        restore-keys: 'bazel-repositories-

          '
    - continue-on-error: true
      name: Cache Bazel results
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
      with:
        key: bazel-actions-${{runner.os}}-${{github.sha}}
        path: ~/bazel-action-cache
        restore-keys: 'bazel-actions-${{runner.os}}-

          '
    - continue-on-error: true
      name: Configure bazel
      run: 'echo "build --repository_cache=~/bazel-repository-cache" >> ~/.bazelrc

        echo "build --disk_cache=~/bazel-action-cache" >> ~/.bazelrc

        echo "build --verbose_failures" >> ~/.bazelrc

        bazel info

        '
    - continue-on-error: true
      if: matrix.test-target == 'default'
      name: Run tests
      run: ./build_test.sh CI
    - continue-on-error: true
      if: matrix.test-target == 'samples'
      name: Run samples tests
      run: "if [[ -f \"./build_test_samples.sh\" ]]; then\n  ./build_test_samples.sh\
        \ CI\nfi"
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        test-target:
        - default
        - samples
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
permissions: read-all
